const types = {
  GET_CRYPTO_DATA: "GET_CRYPTO_DATA",
  REMOVE_CRYPTO_FROM_TABLE: "REMOVE_CRYPTO_FROM_TABLE",
  ADD_CRYPTO_TO_TABLE: "ADD_CRYPTO_TO_TABLE",
  SET_CRYPTO_PRICE: "SET_CRYPTO_PRICE",
  APPEND_CRYPTO_DATA: "APPEND_CRYPTO_DATA"
};

export default types;
